# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Ergebnis\Environment\SystemVariables:
        autowire: true
    Ergebnis\Environment\Variables: '@Ergebnis\Environment\SystemVariables'

    # Definition of the custom commands which will be lazy-loaded.
    App\Command\Additional\RegisterCommand:
        tags:
            - { name: 'console.command', command: 'origami:register' }
            - { name: 'console.command', command: 'register' }

    App\Command\Additional\RegistryCommand:
        tags:
            - { name: 'console.command', command: 'origami:registry' }
            - { name: 'console.command', command: 'registry' }

    App\Command\Contextual\Services\ElasticsearchCommand:
        tags:
            - { name: 'console.command', command: 'origami:elasticsearch' }
            - { name: 'console.command', command: 'elasticsearch' }

    App\Command\Contextual\Services\MysqlCommand:
        tags:
            - { name: 'console.command', command: 'origami:mysql' }
            - { name: 'console.command', command: 'mysql' }

    App\Command\Contextual\Services\NginxCommand:
        tags:
            - { name: 'console.command', command: 'origami:nginx' }
            - { name: 'console.command', command: 'nginx' }

    App\Command\Contextual\Services\PhpCommand:
        tags:
            - { name: 'console.command', command: 'origami:php' }
            - { name: 'console.command', command: 'php' }

    App\Command\Contextual\Services\RedisCommand:
        tags:
            - { name: 'console.command', command: 'origami:redis' }
            - { name: 'console.command', command: 'redis' }

    App\Command\Contextual\DataCommand:
        tags:
            - { name: 'console.command', command: 'origami:data' }
            - { name: 'console.command', command: 'data' }

    App\Command\Contextual\LogsCommand:
        tags:
            - { name: 'console.command', command: 'origami:logs' }
            - { name: 'console.command', command: 'logs' }

    App\Command\Contextual\PsCommand:
        tags:
            - { name: 'console.command', command: 'origami:ps' }
            - { name: 'console.command', command: 'ps' }

    App\Command\Contextual\RestartCommand:
        tags:
            - { name: 'console.command', command: 'origami:restart' }
            - { name: 'console.command', command: 'restart' }

    App\Command\Contextual\RootCommand:
        tags:
            - { name: 'console.command', command: 'origami:root' }
            - { name: 'console.command', command: 'root' }

    App\Command\Contextual\StopCommand:
        tags:
            - { name: 'console.command', command: 'origami:stop' }
            - { name: 'console.command', command: 'stop' }

    App\Command\Main\InstallCommand:
        tags:
            - { name: 'console.command', command: 'origami:install' }
            - { name: 'console.command', command: 'install' }

    App\Command\Main\PrepareCommand:
        tags:
            - { name: 'console.command', command: 'origami:prepare' }
            - { name: 'console.command', command: 'prepare' }

    App\Command\Main\StartCommand:
        tags:
            - { name: 'console.command', command: 'origami:start' }
            - { name: 'console.command', command: 'start' }

    App\Command\Main\UninstallCommand:
        tags:
            - { name: 'console.command', command: 'origami:uninstall' }
            - { name: 'console.command', command: 'uninstall' }

    App\Command\Main\UpdateCommand:
        tags:
            - { name: 'console.command', command: 'origami:update' }
            - { name: 'console.command', command: 'update' }
