name: Continuous Deployment

on:
  push:
    branches: ['master']

jobs:
  tests:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install system requirements'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mbstring, xml
          coverage: none
        env:
          fail-fast: true

      - name: 'Load the keys used to deploy the PHAR archive'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SIGNING_KEY }}" | gpg --import

      - name: 'Configure the committer identity'
        run: |
          git config --global user.email "info@ajardin.fr"
          git config --global user.name "Alexandre Jardin"
          git config --global commit.gpgsign "true"
          git config --global user.signingkey "405DC05A6F8FFBA9"

      - name: 'Install Composer dependencies'
        run: |
          composer validate --strict --ansi
          composer install --optimize-autoloader --classmap-authoritative --ansi

      - name: 'Compile the PHAR archive'
        run: make box

      - name: 'Prepare the local Git repository which contains the PHAR archive'
        run: |
          git clone git@github.com:ajardin/origami.git /tmp/origami
          mkdir -p /tmp/origami/bin/
          cp ./build/origami.phar /tmp/origami/bin/origami

      - name: 'Update the remote Git repository which contains the PHAR archive'
        run: |
          cd /tmp/origami
          git add bin/origami
          git commit --message="Update to commit https://github.com/ajardin/origami-source/commit/${{ github.sha }}"
          git push origin HEAD:master
